### ISSUE TITLE
Filesystem.openForRead always returns a file descriptor of zero

### ISSUE THREAD

**Issue by austinfrey** [jedisct1/wasa#2]
I can not seem to open a regular file for reading. In this example, i call `Filesystem.openForRead('./foo')` on a local file in the directory, but this method always returns `0` or the stdin file descriptor. am I using these methods as intended or am i missing something?

Thanks!

```ts
import "allocator/arena";

import { Console, IO, Filesystem } from "./wasa";
import { wasiabort } from './env'

// entrypoint for wasmer
export function _start(): void {
  let fd = Filesystem.openForRead('./foo')
  Console.log(fd.toString()) // prints '0'
  let str = IO.readString(fd)
  Console.log(str.slice(0, str.length - 1).split('').reverse().join(''))
}
```

**Comment by jedisct1** [comment]
Hi Austin,

WASI requires files and directories to be pre-opened before they can be used.

Since you are using wasmer, did you use a command-line option such as `--dir .`?

**Comment by austinfrey** [comment]
@jedisct1 this worked perfectly! thanks for pointing me in the right direction!
