### ISSUE TITLE
How to apply the bindings.json

### ISSUE THREAD

**Issue by FranklinWaller** [jedisct1/wasa#5]
It's not really clear how to apply the bindings.json or which tool is used for this.

**Comment by MaxGraey** [comment]
`bindings.json` used by lucet

**Comment by FranklinWaller** [comment]
Nice thanks!

**Comment by jedisct1** [comment]
Yes, this is only useful for the Lucet compiler.

Lucet compiles WebAssembly code ahead of time, so if a symbol is referenced, it has to be defined somewhere. It can’t be a runtime error.

And the JSON file is a way to list all the symbols defined externally (“imports”), as well as what names they map to.
